FROM elixir:1.18.3-otp-27-slim

# Set environment variables
ENV ENVIRONMENT=test
ENV MIX_ENV=test

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Install Hex and Rebar
RUN mix local.hex --force

# Copy mix files and install dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get

# Copy the rest of the application code
COPY . .

# Compile the application
RUN mix compile

ENTRYPOINT ["docker-entrypoint.sh"]

# Run tests
CMD ["mix", "test"]
